### ISSUE TITLE
ImportError: undefined symbol when importing grid as _ext in voxel_helpers.py

### ISSUE THREAD

**Issue by Yuhanelle** [zju3dv/Vox-Fusion#38]
When I run demo/run.py, the following error shows up. 
Traceback (most recent call last):
  File "demo/run.py", line 8, in <module>
    from SLAM import VoxSLAM
  File "/home/asblab/yuhanz/Vox_join/src/SLAM.py", line 9, in <module>
    from mapping import Mapping
  File "/home/asblab/yuhanz/Vox_join/src/mapping.py", line 13, in <module>
    from network.render_helpers import bundle_adjust_frames
  File "/home/asblab/yuhanz/Vox_join/src/network/render_helpers.py", line 6, in <module>
    from network.voxel_helpers import ray_intersect, ray_sample
  File "/home/asblab/yuhanz/Vox_join/src/network/voxel_helpers.py", line 17, in <module>
    import grid as _ext
ImportError: /home/asblab/miniconda3/envs/yuhan/lib/python3.7/site-packages/grid.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops4ones4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEE

I tried to do "pip install ." instead of sh install.sh, it still gave me the same error. I am wondering what's wrong with my installation?

**Comment by xingruiy** [comment]
what's your torch and python version?
