### ISSUE TITLE
FileNotFoundError: /home/xyz/Github/Vox-Fusion/room0/traj.txt not found.

### ISSUE THREAD

**Issue by zerolfq** [zju3dv/Vox-Fusion#4]
Traceback (most recent call last):
  File "/home/xyz/Github/Vox-Fusion/demo/run.py", line 21, in <module>
    slam = VoxSLAM(args)
  File "/home/xyz/Github/Vox-Fusion/src/voxslam.py", line 33, in __init__
    self.data_stream = get_dataset(args)
  File "/home/xyz/Github/Vox-Fusion/src/utils/import_util.py", line 6, in get_dataset
    return Dataset.DataLoader(**args.data_specs)
  File "/home/xyz/Github/Vox-Fusion/src/dataset/replica.py", line 18, in __init__
    self.gt_pose = self.load_gt_pose()
  File "/home/xyz/Github/Vox-Fusion/src/dataset/replica.py", line 36, in load_gt_pose
    gt_pose = np.loadtxt(gt_file)
  File "/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1313, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/numpy/lib/npyio.py", line 955, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /home/xyz/Github/Vox-Fusion/room0/traj.txt not found.
/home/xyz/anaconda3/envs/vox/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
FileNotFoundError: /home/xyz/Github/Vox-Fusion/room0/traj.txt not found.
I can't find this file in Replica Dataset

**Comment by zhaihongjia** [comment]
Hi, you can download the Replica dataset at https://cvg-data.inf.ethz.ch/nice-slam/vis/Replica/.

**Comment by zhaihongjia** [comment]
@zerolfq Hi, you can download the Replica dataset at https://cvg-data.inf.ethz.ch/nice-slam/vis/Replica/.

**Comment by zerolfq** [comment]
> @zerolfq Hi, you can download the Replica dataset at https://cvg-data.inf.ethz.ch/nice-slam/vis/Replica/.

Sorry, I still can't find this file at this link。

**Comment by garylidd** [comment]
Thanks for trying out our code.

we use the Replica dataset generated in NICE-SLAM project, you can download by running this script https://github.com/cvg/nice-slam/blob/master/scripts/download_replica.sh and change the data_path in config file.

**Comment by zerolfq** [comment]
An error occurred when I could not compile the third-party library


FAILED: /home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/build/temp.linux-x86_64-3.9/src/octree.o 
c++ -MMD -MF /home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/build/temp.linux-x86_64-3.9/src/octree.o.d -pthread -B /home/xyz/anaconda3/envs/vox/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/xyz/anaconda3/envs/vox/include -I/home/xyz/anaconda3/envs/vox/include -fPIC -O2 -isystem /home/xyz/anaconda3/envs/vox/include -fPIC -I./include -I/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/include -I/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/include/TH -I/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/include/THC -I/home/xyz/anaconda3/envs/vox/include -I/home/xyz/anaconda3/envs/vox/include/python3.9 -c -c /home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/src/octree.cpp -o /home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/build/temp.linux-x86_64-3.9/src/octree.o -O2 -I./include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=grid -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/src/octree.cpp:6:10: fatal error: octree.h: 没有那个文件或目录
    6 | #include "octree.h"
      |          ^~~~~~~~~~
compilation terminated.
[2/6] c++ -MMD -MF /home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/build/temp.linux-x86_64-3.9/src/binding.o.d -pthread -B /home/xyz/anaconda3/envs/vox/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/xyz/anaconda3/envs/vox/include -I/home/xyz/anaconda3/envs/vox/include -fPIC -O2 -isystem /home/xyz/anaconda3/envs/vox/include -fPIC -I./include -I/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/include -I/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/include/TH -I/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/include/THC -I/home/xyz/anaconda3/envs/vox/include -I/home/xyz/anaconda3/envs/vox/include/python3.9 -c -c /home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/src/binding.cpp -o /home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/build/temp.linux-x86_64-3.9/src/binding.o -O2 -I./include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=grid -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/build/temp.linux-x86_64-3.9/src/binding.o 
c++ -MMD -MF /home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/build/temp.linux-x86_64-3.9/src/binding.o.d -pthread -B /home/xyz/anaconda3/envs/vox/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/xyz/anaconda3/envs/vox/include -I/home/xyz/anaconda3/envs/vox/include -fPIC -O2 -isystem /home/xyz/anaconda3/envs/vox/include -fPIC -I./include -I/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/include -I/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/include/TH -I/home/xyz/anaconda3/envs/vox/lib/python3.9/site-packages/torch/include/THC -I/home/xyz/anaconda3/envs/vox/include -I/home/xyz/anaconda3/envs/vox/include/python3.9 -c -c /home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/src/binding.cpp -o /home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/build/temp.linux-x86_64-3.9/src/binding.o -O2 -I./include -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=grid -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/home/xyz/Github/Vox-Fusion/third_party/sparse_voxels/src/binding.cpp:6:10: fatal error: intersect.h: 没有那个文件或目录
    6 | #include "intersect.h"


Sorry, I don't really understand setup

**Comment by garylidd** [comment]
We did find this problem in some compilation environment, please refer to #1 for workaround solutions.
