### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory [W CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors] [W CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

### ISSUE THREAD

**Issue by antonpapa** [zju3dv/Vox-Fusion#51]
insert keyframe
******* tracking process started! *******
tracking frame:  53%|██████████████████████████████████████████████████▍                                             | 52/99 [00:41<00:43,  1.07it/s]insert keyframe
********** current num kfs: 2 **********
tracking frame: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [01:28<00:00,  1.12it/s]
========== stop_mapping set ==========
******* tracking process died *******
Process Process-2:
Traceback (most recent call last):
  File "/home/acc/anaconda3/envs/vox_fusion/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/acc/anaconda3/envs/vox_fusion/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/acc/Vox-Fusion/src/mapping.py", line 87, in spin
    tracked_frame = kf_buffer.get()
                    ^^^^^^^^^^^^^^^
  File "/home/acc/anaconda3/envs/vox_fusion/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acc/anaconda3/envs/vox_fusion/lib/python3.11/site-packages/torch/multiprocessing/reductions.py", line 495, in rebuild_storage_fd
    fd = df.detach()
         ^^^^^^^^^^^
  File "/home/acc/anaconda3/envs/vox_fusion/lib/python3.11/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acc/anaconda3/envs/vox_fusion/lib/python3.11/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acc/anaconda3/envs/vox_fusion/lib/python3.11/multiprocessing/connection.py", line 518, in Client
    c = SocketClient(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/acc/anaconda3/envs/vox_fusion/lib/python3.11/multiprocessing/connection.py", line 646, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
[W CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[W CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
Hi,the same problem occurred in #49,and I have tried the method(modified line 83 of the src/mapping. py file "while True:" as "while len(self.keyframe_graph) < 40:"),but it doesn't work,does anyone knows the reason,tks.

**Comment by antonpapa** [comment]
OK guys,problem is solved,see the problem #23,bro got the same question ,code is ok,but my computer is too suck.If you guys have the same problem could try to make the   end_frame:  in yaml smaller,and the only problem is that I should get a better cpu and a better gpu (lol).

**Comment by JiePaiWs** [comment]
hello,guys,i wonder how you have solved the problem.I get the same problem,i do hope you could help me
